### ISSUE TITLE
Using External HTML template

### ISSUE THREAD

**Issue by newargus** [tablelist/angular-slideout-panel#1]
Hi, 

First good start...

I've tried to use an external html page as template sush as 'views/ModalTemplate.html' for template, but it raised an error. 
Any idea, why ?

Thanks,

**Comment by officert** [comment]
hey @newargus could you post the error you're getting?

**Comment by officert** [comment]
the `template` option is actually for inline templates and must be a string. If it's a URL to a template then you should use the `templateUrl` option.

Just realizing I didn't put up any documentation for the `angularSlideOutPanel` service's `.open()` function and the `options` object it takes. Going to add some additional information to https://tablelist.github.io/angular-slideout-panel/#example

**Comment by officert** [comment]
updated docs can be found here:

https://tablelist.github.io/angular-slideout-panel/#docs
